version: "3.7"

services:
  mysql:
    build: ./mysql
    command:
      - --sql-mode=NO_ENGINE_SUBSTITUTION
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test"

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - "8080:80"

  php:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql

volumes:
  db_data: {}
